apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: market
  name: market
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: market
  template:
    metadata:
      labels:
        app.kubernetes.io/name: market
    spec:
      containers:
        - name: market
          image: 716160859964.dkr.ecr.us-east-1.amazonaws.com/athena-market:latest
          ports:
            - containerPort: 8000
              protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: Always

          env:
            - name: NEXT_PUBLIC_INFURA_PROJECT_ID
              value: 953659398bd94786a13b867b5d3b5700

            - name: NEXT_PUBLIC_MARKET_FEE_ADDRESS
              value: 0x1BDD96Fa11b44b392B6A760640A34504585c3b29

      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
